const uuid = require("uuid");

const meals = [
	{
		meal_id: uuid.v4(),
		meal_image: "https://imgur.com/5H9JNVN.jpg",
		meal_name: "Breakfast Sandwich",
		meal_category: "Breakfast",
		meal_description:
			"Amazing bacon, egg and cheese with a hash brown on a roll",
	},
	{
		meal_id: uuid.v4(),
		meal_image: "https://imgur.com/IywOABd.jpg",
		meal_name: "Buffalo Chicken Dip",
		meal_category: "Snack",
		meal_description: "Fantastic buffalo chicken dip appetizer",
	},
	{
		meal_id: uuid.v4(),
		meal_image: "https://imgur.com/lrOVwgK.jpg",
		meal_name: "Caesar Salad",
		meal_category: "Lunch",
		meal_description: "Delicious homemade caesar salad",
	},
	{
		meal_id: uuid.v4(),
		meal_image: "https://imgur.com/RheXwZO.jpg",
		meal_name: "Charcuterie Board",
		meal_category: "Snack",
		meal_description: "Wonderful board of meets & cheeses",
	},
	{
		meal_id: uuid.v4(),
		meal_image: "https://imgur.com/q3v9GdH.jpg",
		meal_name: "Chicken Parm",
		meal_category: "Dinner",
		meal_description: "Homemade chicken parm made from scratch",
	},
	{
		meal_id: uuid.v4(),
		meal_image: "https://imgur.com/u3ahaL7.jpg",
		meal_name: "Chips & Guac",
		meal_category: "Snack",
		meal_description:
			"Delicious chips & guac we got at a local Mexican restaurant",
	},
	{
		meal_id: uuid.v4(),
		meal_image: "https://imgur.com/DUajUHP.jpg",
		meal_name: "Chocolate Cake",
		meal_category: "Dessert",
		meal_description: "Fantastic chocolate cake from our favorite local bakery",
	},
	{
		meal_id: uuid.v4(),
		meal_image: "https://imgur.com/Coi7Xqz.jpg",
		meal_name: "Cinnamon Buns",
		meal_category: "Breakfast",
		meal_description: "Homemade cinnabon buns are as good as it gets!",
	},
	{
		meal_id: uuid.v4(),
		meal_image: "https://imgur.com/Pj6De7f.jpg",
		meal_name: "Garlic Bread",
		meal_category: "Snack",
		meal_description: "Best garlic bread around made from scratch!",
	},
	{
		meal_id: uuid.v4(),
		meal_image: "https://imgur.com/s2bll1e.jpg",
		meal_name: "Gnocchi",
		meal_category: "Dinner",
		meal_description: "Gnocchi from our facorite Italian restaurant",
	},
	{
		meal_id: uuid.v4(),
		meal_image: "https://imgur.com/nNxXBU3.jpg",
		meal_name: "Greek Salad",
		meal_category: "Lunch",
		meal_description: "Delicious salad from a local greek restaurant",
	},
	{
		meal_id: uuid.v4(),
		meal_image: "https://imgur.com/LBWWMbD.jpg",
		meal_name: "Greek Gyros",
		meal_category: "Lunch",
		meal_description: "Fantastic gyros from a food truck",
	},
	{
		meal_id: uuid.v4(),
		meal_image: "https://imgur.com/ntwQe6p.jpg",
		meal_name: "Grilled Cheese",
		meal_category: "Lunch",
		meal_description: "Delicious grilled cheese with tomato for lunch",
	},
	{
		meal_id: uuid.v4(),
		meal_image: "https://imgur.com/U52a8Uf.jpg",
		meal_name: "Ice Cream Sundae",
		meal_category: "Dessert",
		meal_description: "Best ice cream around for our favorite ice cream parlor",
	},
	{
		meal_id: uuid.v4(),
		meal_image: "https://imgur.com/J2h6lRo.jpg",
		meal_name: "Italian Sub",
		meal_category: "Lunch",
		meal_description: "Best cold cut sandwich from the best deli around",
	},
	{
		meal_id: uuid.v4(),
		meal_image: "https://imgur.com/8KmSuoE.jpg",
		meal_name: "Lobster Roll",
		meal_category: "Lunch",
		meal_description: "Lobster roll we got from a place in Maine",
	},
	{
		meal_id: uuid.v4(),
		meal_image: "https://imgur.com/aNN3rHi.jpg",
		meal_name: "New England Clam Chowder",
		meal_category: "Lunch",
		meal_description: "Best soup around from our favorite lunch spot",
	},
	{
		meal_id: uuid.v4(),
		meal_image: "https://imgur.com/Ggeo7SC.jpg",
		meal_name: "Pancakes",
		meal_category: "Breakfast",
		meal_description:
			"Pancakes made from scratch are the best treat on a Saturday morning!",
	},
	{
		meal_id: uuid.v4(),
		meal_image: "https://imgur.com/ElSsrU9.jpg",
		meal_name: "Pizza",
		meal_category: "Dinner",
		meal_description: "Best pizza of all time from a place in New Haven, CT",
	},
	{
		meal_id: uuid.v4(),
		meal_image: "https://imgur.com/cdrRa7s.jpg",
		meal_name: "Spaghetti",
		meal_category: "Dinner",
		meal_description:
			"Hands down the best spaghetti ever from a restaurant in NYC",
	},
	{
		meal_id: uuid.v4(),
		meal_image: "https://imgur.com/jq0R9ix.jpg",
		meal_name: "Waffles",
		meal_category: "Breakfast",
		meal_description: "Waffles from my favorite local diner",
	},
	{
		meal_id: uuid.v4(),
		meal_image: "https://imgur.com/xcUbC0N.jpg",
		meal_name: "Buffalo Wings",
		meal_category: "Snack",
		meal_description: "Delicious Buffalo wings",
	},
	{
		meal_id: uuid.v4(),
		meal_image: "https://imgur.com/56MPSdZ.jpg",
		meal_name: "French Toast",
		meal_category: "Breakfast",
		meal_description: "Outstanding french toast that we made last weekend",
	},
];
